theme: minima
title: Curso GitHub Pages.
author: Iván Fernando Vázquez López
description: Este curso es parte del curso propedéutico de la Maestría en Ciencia de Datos de la Universidad de Sonora. 
